name: cafeteria
description: Cafeteria order automatization

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^3.2.0
  outline_material_icons: ^0.1.1
  google_fonts: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Calistoga
      fonts:
        - asset: fonts/Calistoga/Calistoga-Regular.ttf
          weight: 400
    - family: JosefinSans
      fonts:
        - asset: fonts/JosefinSans/JosefinSans-Bold.ttf
          weight: 700
        - asset: fonts/JosefinSans/JosefinSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/JosefinSans/JosefinSans-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/JosefinSans/JosefinSans-Light.ttf
          weight: 300
        - asset: fonts/JosefinSans/JosefinSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/JosefinSans/JosefinSans-Regular.ttf
          weight: 400
        - asset: fonts/JosefinSans/JosefinSans-SemiBold.ttf
          weight: 500
        - asset: fonts/JosefinSans/JosefinSans-SemiBoldItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/JosefinSans/JosefinSans-Thin.ttf
          weight: 200
        - asset: fonts/JosefinSans/JosefinSans-ThinItalic.ttf
          weight: 200
          style: italic