name: cafeteria
description: Cafeteria order automatization

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^3.2.0
  outline_material_icons: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: BebasNeue
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf
    - family: SulphurPoint
      fonts:
        - asset: fonts/SulphurPoint-Regular.ttf
          weight: 400
        - asset: fonts/SulphurPoint-Light.ttf
          weight: 300
        - asset: fonts/SulphurPoint-Bold.ttf
          weight: 700
  